train: True
epochs: 30
batch_size: 256
sequence_len: 10
lstm_size: 128
word_embed_dims: 128
drop_out_prob: 0
hidden_dim: 32

lr: 0.0001
gamma: 0.99
lmbda: 0.95
clip: 0.1
entropy_act_param: 0.2
value_param: 1

policy_qa_param: 0.25
advantage_qa_param: 1
entropy_qa_param: 0.5

train_episodes: 7500
test_episodes: 0

train_log_interval: 250
test_log_interval: 250
log_questions: True

train_env_name: "MiniGrid-DoorKey-5x5-v0"
test_env_name: "MiniGrid-DoorKey-8x8-v0"

ans_random: 0

undefined_error_reward: 0
syntax_error_reward: -0.2
defined_q_reward: 0.2
defined_q_reward_test : 0

pre_trained_lstm: True

use_mem: True
use_seed: False
exp_mem: True
baseline: False
film: False
wandb: True
notes: "Locked Room Film"
load: False
name: "locked_room film"
