train: True
epochs: 30
batch_size: 256
sequence_len: 10
lstm_size: 128
word_embed_dims: 128
drop_out_prob: 0
hidden_dim: 32

lr: 0.0005
gamma: 0.99
lmbda: 0.95
clip: 0.2
entropy_act_param: 0.1
value_param: 1

policy_qa_param: 0.25
advantage_qa_param: 1
entropy_qa_param: 0.2

train_episodes: 3
test_episodes: 3

train_log_interval: 1
test_log_interval: 1
log_questions: False

train_env_name: "MiniGrid-FourRooms-v0"
# train_env_name: "MiniGrid-FourRooms-v0"
test_env_name: "MiniGrid-FourRooms-v0"

ans_random: 0

undefined_error_reward: 0
syntax_error_reward: -0.2
defined_q_reward: 0.2
defined_q_reward_test : 0

pre_trained_lstm: True

use_mem: True
use_seed: False
exp_mem: True
baseline: True
film: False
wandb: True
notes: "trial film"
load: False
name: "agent_trial"