state_noun =   "door " .
noun =  state_noun | "wall "  | "floor " |  "key " | "ball " | "box " | "goal "  | "lava "  | "agent " .
verb = "is " .
state = "open " | "closed " | "locked " .
direction = "north " | "south " | "west " | "east " .
adjective = "red " | "green " | "blue "| "purple "| "yellow " | "grey " .

noun_phrase = adjective noun .
direction_sentence = noun_phrase verb direction.

state_sentence = adjective state_noun verb state.