noun = "unseen "| "empty " | "wall "  | "floor " | "door "  |  "key " | "ball " | "box " | "goal "  | "lava "  | "agent " .
verb = "is " .
state = "open " | "closed " | "locked " .
direction = "north " | "south " | "west " | "east " .
adjective = "red " | "green " | "blue "| "purple "| "yellow " | "grey " .

noun_phrase = adjective noun .
operator = state | direction .
sentence = noun_phrase verb operator.

main = sentence .
